name: Docker Publish Automatic

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print Tags
        run: git tag -l

      - name: Checkout the agora-token-service repo
        uses: actions/checkout@v2
        with:
          repository: AgoraIO-Community/agora-token-service
          path: agora-token-service

      - name: Print Tags
        run: git -C agora-token-service tag -l

      - name: Get first stable tag (eg v1.0.0) which is not used by this repository
        id: get_tag
        run: |
            for tag in $(git -C agora-token-service tag -l | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -rV); do
                if ! git tag -l | grep -q $tag; then
                    echo "Found tag $tag"
                    echo ::set-output name=tag::$tag
                    exit 0
                fi
            done
            echo "No tag found"
            exit 1

      - name: Get Github Release Data
        id: release_data
        uses: KevinRohn/github-full-release-data@v2
        with:
          repository: AgoraIO-Community/agora-token-service
          version: ${{ steps.get_tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_data.outputs.tag_name }}
          release_name: ${{ steps.release_data.outputs.tag_name }}
          body: ${{ steps.release_data.outputs.body }}
          draft: false
          prerelease: false



