name: Docker Publish Automatic

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true

      - name: Get Latest Github Release
        id: agora_release
        uses: KevinRohn/github-full-release-data@v2
        with:
          repository: AgoraIO-Community/agora-token-service
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure the release is not already published via git tag -l
        run: |
          if git tag -l | grep -q ${{ steps.agora_release.outputs.tag_name }}; then
              echo "Tag already exists, exiting"
              exit 0
          fi

      - name: Create a release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.agora_release.outputs.tag_name }}
          release_name: ${{ steps.agora_release.outputs.tag_name }}
          body: |
            ${{ steps.agora_release.outputs.body }}
          draft: false
          prerelease: false



