name: Docker Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
